# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - package
  - e2e
  - cleanup

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

unit-test:
  stage: test
  image: python:3.11-alpine
  script:
    - cd backend
    - pip install pytest coverage
    - pip install -r requirements.txt
    - python -m coverage run -m pytest --junitxml=report.xml tests/
    - python -m coverage report
    - python -m coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: backend/report.xml
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage.xml

containerize:
  stage: package
  image: docker:20.10.15-dind
  variables:
    loc: "${CI_COMMIT_BRANCH}${CI_COMMIT_TAG}"
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/enigma_back:${loc} backend/
    - docker build -t ${CI_REGISTRY_IMAGE}/enigma_front:${loc} frontend/

    - docker push ${CI_REGISTRY_IMAGE}/enigma_back:${loc}
    - docker push ${CI_REGISTRY_IMAGE}/enigma_front:${loc}
  after_script:
    - docker rmi ${CI_REGISTRY_IMAGE}/enigma_back:${loc}
    - docker rmi ${CI_REGISTRY_IMAGE}/enigma_front:${loc}

e2e-test:
  image: docker:20.10.15-dind
  variables:
    loc: "${CI_COMMIT_BRANCH}${CI_COMMIT_TAG}"
  services:
    - name: ${CI_REGISTRY_IMAGE}/enigma_front:${loc}
      alias: frontend

    - name: ${CI_REGISTRY_IMAGE}/enigma_back:${loc}
      alias: backend
  stage: e2e
  script:
    - apk add --no-cache python3 py3-pip firefox
    - pip3 install behave selenium
    - pip3 install webdriver_manager
    - python3 -m behave E2E/



remove-container:
  variables:
    loc: "${CI_COMMIT_BRANCH}${CI_COMMIT_TAG}"
  stage: cleanup
  image: docker:20.10.15-dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - wget -O /usr/bin/reg https://github.com/genuinetools/reg/releases/download/v0.16.0/reg-linux-amd64
    - chmod +x /usr/bin/reg
    - reg rm ${CI_REGISTRY_IMAGE}/enigma_back:${loc}
    - reg rm ${CI_REGISTRY_IMAGE}/enigma_front:${loc}
  except:
    variables:
      - $CI_COMMIT_TAG
