# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
  - test
  - package
  - e2e
  - cleanup

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

# Uncomment once test are added
#unit-test:
#  stage: test
#  image: python:3.11-alpine
#  script:
#    - pip install pipenv
#    - pipenv install --dev
#    - pipenv run coverage run -m pytest --junitxml=report.xml backend/tests/unit
#    - pipenv run coverage report
#    - pipenv run coverage xml
#  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
#  artifacts:
#    reports:
#      junit: report.xml
#      coverage_report:
#        coverage_format: cobertura
#        path: coverage.xml

containerize:
  stage: package
  image: docker:20.10.15-dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/enigma_back:${CI_COMMIT_BRANCH} backend/
    - docker build -t ${CI_REGISTRY_IMAGE}/enigma_front:${CI_COMMIT_BRANCH} frontend/

    - docker push ${CI_REGISTRY_IMAGE}/enigma_back:${CI_COMMIT_BRANCH}
    - docker push ${CI_REGISTRY_IMAGE}/enigma_front:${CI_COMMIT_BRANCH}
  after_script:
    - docker rmi ${CI_REGISTRY_IMAGE}/enigma_back:${CI_COMMIT_BRANCH}
    - docker rmi ${CI_REGISTRY_IMAGE}/enigma_front:${CI_COMMIT_BRANCH}

e2e-test:
  stage: e2e
  image: docker:20.10.15-dind
  variables:
    #CONTAINER_IMAGE: ${CI_REGISTRY_IMAGE}/enigma:${CI_COMMIT_REF_SLUG}
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - apk add firefox
    - apk add --update python3
    - python3 -m ensurepip
    - pip3 install pipenv
    - pipenv install --dev
    - pipenv run behave E2E
#  after_script:
#    - docker rmi ${CI_REGISTRY_IMAGE}/enigma_back:${CI_COMMIT_BRANCH}
#    - docker rmi ${CI_REGISTRY_IMAGE}/enigma_front:${CI_COMMIT_BRANCH}


remove-container:
  stage: cleanup
  image: docker:20.10.15-dind
  before_script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - wget -O /usr/bin/reg https://github.com/genuinetools/reg/releases/download/v0.16.0/reg-linux-amd64
    - chmod +x /usr/bin/reg
    - reg rm ${CI_REGISTRY_IMAGE}/enigma_back:${CI_COMMIT_BRANCH}
    - reg rm ${CI_REGISTRY_IMAGE}/enigma_front:${CI_COMMIT_BRANCH}
  except:
    variables:
      - $CI_COMMIT_TAG
