version: "3"
services:
  backend:
    build: backend/
    ports:
      - "25500:25500"
    volumes:
      - data:/home/developer/data

  frontend:
    build: frontend/
    ports:
      - "80:80"

volumes:
  data: